env:
  browser: true
  es2021: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  camelcase: ["error", {ignoreDestructuring: true}]  
  import/no-unresolved: 0
  no-param-reassign: 0
  no-shadow: ["error", { "builtinGlobals": false, "hoist": "functions", "allow": [], "ignoreOnInitialization": false }]
  consistent-return: 0
  no-unused-vars: 0
